services:
  math-app:
    image: node:24
    ports:
      - "3000:3000"
    working_dir: "/app"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    command: 'bash -c "npm ci && npm run dev"'
